/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unibo.wenvusage;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    // eseguito prima di ogni test
    @Before public void setup(){
        System.out.println("Setup");
    }

    @After public void closer(){
        System.out.println("Closing");
    }

    @Test public void testAppHasAGreeting() {

        System.out.println("Test 1");

        App classUnderTest = new App();

        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    // fallisce sempre
    @Test public void test2() {
        System.out.println("Test 2");
        //fail();
    }

    // passa sempre
    @Test public void test3() {
        System.out.println("Test 3");
        assertTrue(true);
    }
}
